config/routes.rb
Prediction::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions
  resources :users
  resources :events do
    resources :orders
  end
  get "welcome/index"
  get "/about" => "welcome#about"
  get "welcome/about"
  root to: "welcome#index"

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  validates :contract_price, :numericality => {:only_integer => true}
  belongs_to :buy_order, :foreign_key => "buy_order_id", :class_name => "Order"
  belongs_to :sell_order, :foreign_key => "sell_order_id", :class_name => "Order"
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  
  validates :start_time, :end_time, :presence => true
  validates :title, :description, :avatar, :presence => true
  validates :price, :sell_price, :numericality => {:only_integer => true}
  
  has_many :orders
  has_many :users, :through => :orders
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"

  def can_order?
    self.start_time < Time.zone.now && Time.zone.now < self.end_time if start_time && end_time
  end

  

end

app/models/order.rb
class Order < ActiveRecord::Base

  validates :quantity, :book_price, :numericality => {:only_integer => true}
  validates :option_type, presence: true
  belongs_to :user
  belongs_to :event

  def save_or_create_contract
    if self.first_match
      self.id = Order.last.id + 1
      self.save_as_contract
      return "Contract"
    else
      self.save
      return "Order"
    end
  end  

  def first_match
    if self.option_type == "sell"
      # look for a buy with the same price
      match = Order.where(:book_price => self.book_price, :option_type => "buy").first
    else
      # else, look for a sell with the same price...
      match = Order.where(:book_price => self.book_price, :option_type => "sell").first
    end 
    return match   
  end

  def save_as_contract
    contract = Contract.new
    contract.contract_price = self.book_price
    if self.option_type == "buy"
      contract.buy_order_id = self.id
      contract.sell_order_id = first_match.id
    else
      contract.buy_order_id = first_match.id
      contract.sell_order_id = self.id
    end      
    contract.save
    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :owned_events, :class_name => "Event"
  has_many :orders
  has_many :events, :through => :orders
  
  authenticates_with_sorcery!
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_login
  before_filter :find_event, :only => [:edit, :update, :destroy]
  before_filter :make_sure_owner, :only => [:edit, :update, :destroy]
  

  def index
    @events = Event.all
  end
  
  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    @event.owner_id = current_user.id

    if @event.save
      flash[:notice] = "Event was saved!"
      redirect_to @event
    else
      flash[:error] = "Event wasn't saved."
      render :new
    end
  end

  def edit

    

  end


  def update

    if  @event.update_attributes(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :price, :sell_price, :avatar, :start_time, :end_time)
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def make_sure_owner
    if current_user != @event.owner
       redirect_to events_path
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @orders = @event.orders

  end

  def new
    @order = Order.new

  end

  def create
    @order = current_user.orders.build(order_params)
    @order.quantity = 1
    @order.event_id = params[:event_id]

    # @order = Order.new(order_params)
    # @order.user = current_user
     if type = @order.save_or_create_contract
      if type == "Order" 
        flash[:notice] = "order was saved!"
        redirect_to event_order_path(@order.event, @order)
      elsif type =="Contract"
        redirect_to event_orders_path
      end
     else
      flash[:error] = "order wasn't saved."
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
    @event = @order.event
    @user = @order.user
    @book_price = @order.book_price

    # if @order.save
    #   redirect_to order_path, notice: 'Order successfully'
    # else
    #   render :action => :show
    # end
  end

  def update
  end

  def edit
  end

  private
  def order_params
    params.require(:order).permit(:quantity, :book_price, :option_type)
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new

   end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end 
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!" 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :remember_me)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1 class="header1">EDIT EVENTS</h1>
<div class="editor">
	
	<%= form_for @event do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.label :sell_price %>
	<%= f.text_field :sell_price %>

	<%= f.label :buy_price %>
	<%= f.text_field :price %>

	<%= f.label :avatar %>
	<%= f.file_field :avatar %>

	<%= f.submit nil, :class => "button" %>

</div>

<% end %>

<%= link_to 'Show', event_path(@event) %>
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
  <%= image_tag event.avatar.thumb.url %>
  <p><%= link_to "#{event.title}", event_path(event) %></p>
<% end %>

<%=link_to"Create Event", new_event_path %>
<br/>
<%=link_to "Show Users", users_path %>

app/views/events/new.html.erb
  <%= form_for @event do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :sell_price %>
      <%= f.text_field :sell_price %>

      <%= f.label :buy_price %>
      <%= f.text_field :price %>

      <%= f.label :start_time %>
      <%= f.datetime_local_field :start_time %>

      <%= f.label :end_time %>
      <%= f.datetime_local_field :end_time %>


     
      <%= f.file_field :avatar %>

      <%= f.submit "Save" %>
  <% end %>

  <%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row">
  
  <div class="large-6 columns">
    <h1><%= @event.title %></h1>
    <p><%= @event.description %></p>

    <div class="box">
      <% if @event.can_order? %> 
        <div class="row">
          <%= link_to new_event_order_path(params[:id]) do %>
            <div class="wrapper price">
             
              <p class="trade" id="sell">
                <span class="big-price"><%= @event.sell_price %></span>
                mBTC
              </p>
            </div>
          <% end %>

          <%= link_to new_event_order_path(params[:id]) do %>
           <!--  <div class="wrapper price">
              buy Price
              <p class="trade" id="buy"><%=  @event.price %></p>
            </div> -->
          <% end %>
         </div>
        
        <h3>Started: <%= @event.start_time %></h3>

  
       <h3>Ends: <%= @event.end_time %></h3>

        <% if current_user.id == @event.owner_id %>
          <%= link_to "Edit", edit_event_path(@event) %>
        <% end %>

      <% else %>

        <div data-alert class="alert-box time is over">
          Time is over.
          <!--   <a href="#" class="close">&times;</a> -->
        </div>
        

      <% end %>    
      <div class="Chart">
        <canvas id="myChart" width="400" height="400"></canvas>    
      </div>
    </div>
  </div>

  <div class="large-6 columns">
    <div class="event-avatar-container">
      <%= image_tag @event.avatar %><br>
      <%= link_to 'Back', events_path %>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Sinocast</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="/events">All Events</a></li>
      <li class="has-dropdown">
         <% if current_user %>

         
          <a href="#"><%=current_user.username%></a>
           
        <ul class="dropdown">

          <li> 
            <%= link_to "logout", logout_path %>
         </li>
           <% end %>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <div class="large-12 columns">
        <%=render partial:"layouts/nav"%>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Options#create</h1>
<p>Find me in app/views/options/create.html.erb</p>

app/views/orders/edit.html.erb
<h1>Options#edit</h1>
<p>Find me in app/views/options/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>PREDICTIOUS</h1>
<p>RULES & REGULATIONS!!!!</p><br>

app/views/orders/new.html.erb
<h1>PREDICTIOUS</h1>
  <%= form_for @order, :url => event_orders_path(params[:event_id]) do |f| %>
<div class="editor">
    Quantity: 1

    <%= f.label :book_price %>
    <%= f.text_field :book_price %>

    <%= f.radio_button :option_type, "buy" %>
    <%= f.label :option_type, "Buy" %>
    <%= f.radio_button :option_type, "sell" %>
    <%= f.label :option_type, "Sell" %>
</div>
    

<div class="actions"><%= f.submit nil, :class => "button" %></div>
   

  <% end %>
 
    <%= link_to 'Back', events_path %><br>
   

app/views/orders/show.html.erb
<% if current_user %>

  <h3 class="header3">Execution of an Option</h3>
  <div class="editor">
  name
  <p class="input"><%= @user.username %></p>
  event
  <p class="input"><%= @event.title %></p>
  quantity
  <p class="input"><%= @order.quantity %></p>
  price
  <p class="input"><%= @order.book_price %></p>
</div>
<% end %>

app/views/orders/update.html.erb
<h1>Options#update</h1>
<p>Find me in app/views/options/update.html.erb</p>

app/views/users/index.html.erb
<h3>PREDICTIOUS USERS</h3>
<% @users.each do |user| %>
<p><%= link_to "#{user.username}", user_path(user) %></p>
<% end %>

<%=link_to"Back", events_path %>

app/views/users/new.html.erb
<h1 class="header1">Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <body class="editor">
  <div class="field" id="username">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field" id="email">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field" id="password">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field" id="password_confirmation">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </body>
  </div>
  <div class="actions"><%= f.submit nil, :class => "button" %></div>
<% end %>


<%=link_to "Log in", login_path %>

app/views/users/show.html.erb
<h1 class="header1">good</h1>
<h3 class="header3"><%= @user.username %></h3>
<p><% @user.orders.each do |order| %></p>
Quantity<br>
<%= order.quantity %><br>
Price<br>
<%= order.book_price %><br>
Type<br>
<%= order.option_type %><br>
<% end %>

<%=link_to "handsome users", users_path %>

app/views/welcome/about.html.erb
<h1>PREDICTIOUS--A FORUM FOR WAGERING ABOUT FUTURE EVENTS.</h1>
<p>created by Shan :-)</p>

app/views/welcome/index.html.erb
<div class="row">
  <div class="large-6 columns">
        <h1> Sinocast is a Bitcoin prediction market focused on China.</h1>
  </div>
<!--   <div class="large-6 columns">
    <img src="http://img.diglog.com/img/2011/9/1c20dfcb172c4b09acd2878f36c7cc7f.jpg"><br>
    <!-- <h1><%= link_to 'Show', events_path %></h1>
     -->    
  </div> 
</div>